# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [58]:
### [your code here]
print("NumPy Version:", np.__version__)

NumPy Version: 1.22.2


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [ ]:
### [your code here]
a = np.random.random([2,3,5])

# a = np.random.randint([2,3,5])


### 4. Print a.


In [3]:
### [your code here]
a

array([[[0.58777403, 0.81901867, 0.79995402, 0.36883729, 0.54473152],
        [0.69323313, 0.08158352, 0.68490996, 0.68223402, 0.97099503],
        [0.66610929, 0.41032282, 0.68056279, 0.0754255 , 0.54957704]],

       [[0.07320122, 0.55599524, 0.11609004, 0.80326537, 0.0238672 ],
        [0.95505512, 0.47969781, 0.55986998, 0.67040355, 0.05550204],
        [0.62202502, 0.64860039, 0.27081371, 0.71079485, 0.72934747]]])

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [4]:
### [your code here]
b = np.ones([5,2,3])


### 6. Print b.


In [5]:
### [your code here]
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [7]:
### [your code here]
AB_size = (a.size == b.size)
print(AB_size)

True



### 8. Are you able to add a and b? Why or why not?


In [ ]:
### [your code here]
np.add(a,b)
# the arrays are having different shapes, so they are not suitable for adding 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [22]:
### [your code here]
transpose_b = np.transpose(b)

In [23]:
c = np.reshape(transpose_b, (2,3,5))
c.shape

(2, 3, 5)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
### [your code here]
d = np.add(a,c)
d 
# it works now because the shape of the array b have be transposed and reshaped to the shape of a 

array([[[1.58777403, 1.81901867, 1.79995402, 1.36883729, 1.54473152],
        [1.69323313, 1.08158352, 1.68490996, 1.68223402, 1.97099503],
        [1.66610929, 1.41032282, 1.68056279, 1.0754255 , 1.54957704]],

       [[1.07320122, 1.55599524, 1.11609004, 1.80326537, 1.0238672 ],
        [1.95505512, 1.47969781, 1.55986998, 1.67040355, 1.05550204],
        [1.62202502, 1.64860039, 1.27081371, 1.71079485, 1.72934747]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
### [your code here]
print(f"A = {a}")
print(f"D = {d}")
# the values in a are between 0-1 and in d all the values of a are been increased and stored in d

A = [[[0.58777403 0.81901867 0.79995402 0.36883729 0.54473152]
  [0.69323313 0.08158352 0.68490996 0.68223402 0.97099503]
  [0.66610929 0.41032282 0.68056279 0.0754255  0.54957704]]

 [[0.07320122 0.55599524 0.11609004 0.80326537 0.0238672 ]
  [0.95505512 0.47969781 0.55986998 0.67040355 0.05550204]
  [0.62202502 0.64860039 0.27081371 0.71079485 0.72934747]]]
D = [[[1.58777403 1.81901867 1.79995402 1.36883729 1.54473152]
  [1.69323313 1.08158352 1.68490996 1.68223402 1.97099503]
  [1.66610929 1.41032282 1.68056279 1.0754255  1.54957704]]

 [[1.07320122 1.55599524 1.11609004 1.80326537 1.0238672 ]
  [1.95505512 1.47969781 1.55986998 1.67040355 1.05550204]
  [1.62202502 1.64860039 1.27081371 1.71079485 1.72934747]]]



### 12. Multiply a and c. Assign the result to e.


In [36]:
### [your code here]
e = np.multiply(a,c)
e


array([[[0.58777403, 0.81901867, 0.79995402, 0.36883729, 0.54473152],
        [0.69323313, 0.08158352, 0.68490996, 0.68223402, 0.97099503],
        [0.66610929, 0.41032282, 0.68056279, 0.0754255 , 0.54957704]],

       [[0.07320122, 0.55599524, 0.11609004, 0.80326537, 0.0238672 ],
        [0.95505512, 0.47969781, 0.55986998, 0.67040355, 0.05550204],
        [0.62202502, 0.64860039, 0.27081371, 0.71079485, 0.72934747]]])



### 13. Does e equal to a? Why or why not?


In [ ]:
### [your code here]
check = (e == a)
check
# its equal because the values were multiplied to array that comtains all value in 1 so anything multiplied to 1 will be same 


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [51]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [52]:
### [your code here]
f = np.empty([2, 3, 5])
f

array([[[0.58777403, 0.81901867, 0.79995402, 0.36883729, 0.54473152],
        [0.69323313, 0.08158352, 0.68490996, 0.68223402, 0.97099503],
        [0.66610929, 0.41032282, 0.68056279, 0.0754255 , 0.54957704]],

       [[0.07320122, 0.55599524, 0.11609004, 0.80326537, 0.0238672 ],
        [0.95505512, 0.47969781, 0.55986998, 0.67040355, 0.05550204],
        [0.62202502, 0.64860039, 0.27081371, 0.71079485, 0.72934747]]])




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [53]:
### [your code here]
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i][j][k]
            if value == d_min:
                f[i][j][k] = 0
            elif value == d_max:
                f[i][j][k] = 100
            elif value == d_mean:
                f[i][j][k] = 50
            elif d_min < value < d_mean:
                f[i][j][k] = 25
            elif d_mean < value < d_max:
                f[i][j][k] = 75





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [54]:
### [your code here]
print(d)
print(f)

[[[1.58777403 1.81901867 1.79995402 1.36883729 1.54473152]
  [1.69323313 1.08158352 1.68490996 1.68223402 1.97099503]
  [1.66610929 1.41032282 1.68056279 1.0754255  1.54957704]]

 [[1.07320122 1.55599524 1.11609004 1.80326537 1.0238672 ]
  [1.95505512 1.47969781 1.55986998 1.67040355 1.05550204]
  [1.62202502 1.64860039 1.27081371 1.71079485 1.72934747]]]
[[[ 75.  75.  75.  25.  75.]
  [ 75.  25.  75.  75. 100.]
  [ 75.  25.  75.  25.  75.]]

 [[ 25.  75.  25.  75.   0.]
  [ 75.  25.  75.  75.  25.]
  [ 75.  75.  25.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [56]:
f = np.empty(d.shape, dtype=str)  # create empty string array

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i][j][k]
            if value == d_min:
                f[i][j][k] = 'A'
            elif value == d_max:
                f[i][j][k] = 'E'
            elif value == d_mean:
                f[i][j][k] = 'C'
            elif d_min < value < d_mean:
                f[i][j][k] = 'B'
            elif d_mean < value < d_max:
                f[i][j][k] = 'D'


In [57]:
f

array([[['D', 'D', 'D', 'B', 'D'],
        ['D', 'B', 'D', 'D', 'E'],
        ['D', 'B', 'D', 'B', 'D']],

       [['B', 'D', 'B', 'D', 'A'],
        ['D', 'B', 'D', 'D', 'B'],
        ['D', 'D', 'B', 'D', 'D']]], dtype='<U1')